"""Generate deterministic, offline deliverables from canonical source files."""

from pathlib import Path
import base64
import mimetypes
import re
import zipfile

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
HTML_OUTPUT = DIST / "frontrade-brand-book.html"
ZIP_OUTPUT = DIST / "frontrade-ui-kit.zip"
CSS_PATH = ROOT / "assets/css/styles.css"
JS_PATH = ROOT / "assets/js/app.js"
CSS_URL = re.compile(r"url\(\s*(['\"]?)(.*?)\1\s*\)")
IMAGE_PATH = re.compile(r"assets/(?:images|icons)/[\w./-]+\.(?:webp|svg)")


def source_files():
    """Package only maintained source, documentation and project configuration."""
    paths = [ROOT / name for name in ("index.html", "README.md", ".gitignore", ".editorconfig", ".prettierrc.json")]
    for directory, suffixes in (
        ("assets", {".css", ".js", ".woff2", ".webp", ".svg"}),
        ("docs", {".md", ".png"}),
        ("scripts", {".py"}),
    ):
        paths.extend(path for path in (ROOT / directory).rglob("*") if path.is_file() and path.suffix in suffixes)
    return sorted(paths, key=lambda path: path.relative_to(ROOT).as_posix())


def data_uri(path):
    if not path.is_file() or path.is_symlink():
        raise ValueError(f"Missing or unsupported asset: {path}")
    media_type = "font/woff2" if path.suffix == ".woff2" else mimetypes.guess_type(path.name)[0]
    if not media_type:
        raise ValueError(f"Unknown asset type: {path}")
    return f"data:{media_type};base64," + base64.b64encode(path.read_bytes()).decode("ascii")


def render_html():
    """Embed CSS, JS, fonts and images; fail rather than emit a partial build."""
    def embed_url(match):
        asset = (CSS_PATH.parent / match.group(2)).resolve()
        if not asset.is_relative_to(ROOT / "assets"):
            raise ValueError(f"CSS asset outside assets/: {match.group(2)}")
        return f'url("{data_uri(asset)}")'

    css, asset_count = CSS_URL.subn(embed_url, CSS_PATH.read_text(encoding="utf-8"))
    if asset_count != 4:
        raise ValueError(f"Expected three fonts and one background; found {asset_count} CSS URLs")
    html = (ROOT / "index.html").read_text(encoding="utf-8")
    html, links = re.subn(
        r'<link\b(?=[^>]*href="assets/css/styles\.css(?:\?[^"]*)?")[^>]*>',
        lambda _: "<style>" + css + "</style>", html,
    )
    html, scripts = re.subn(
        r'<script\b(?=[^>]*src="assets/js/app\.js(?:\?[^"]*)?")[^>]*>\s*</script>',
        "", html,
    )
    if links != 1 or scripts != 1:
        raise ValueError(f"Expected one CSS link and one JS script; found {links} / {scripts}")
    logo = "assets/images/logo.webp"
    if html.count(logo) != 2:
        raise ValueError("Expected logo and favicon references")
    def embed_image(match):
        path = (ROOT / match.group(0)).resolve()
        if not path.is_relative_to(ROOT / "assets"):
            raise ValueError(f"Image outside assets/: {match.group(0)}")
        return data_uri(path)

    html = IMAGE_PATH.sub(embed_image, html)
    script = IMAGE_PATH.sub(embed_image, JS_PATH.read_text(encoding="utf-8"))
    script = script.replace("</script", "<\\/script")
    if html.count("</body>") != 1:
        raise ValueError("Expected one closing body tag")
    html = html.replace("</body>", "<script>" + script + "</script>\n</body>")
    return "<!-- Generated by scripts/build.py. Edit index.html and assets/, not this file. -->\n" + html


def build():
    html = render_html()
    files = source_files()
    for path in files:
        if not path.is_file() or path.is_symlink():
            raise ValueError(f"Missing or unsupported source: {path}")
    DIST.mkdir(exist_ok=True)
    HTML_OUTPUT.write_text(html, encoding="utf-8")
    with zipfile.ZipFile(ZIP_OUTPUT, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in files:
            entry = zipfile.ZipInfo("frontrade-cryptos/" + path.relative_to(ROOT).as_posix(), date_time=(1980, 1, 1, 0, 0, 0))
            entry.compress_type = zipfile.ZIP_DEFLATED
            entry.create_system = 3
            entry.external_attr = 0o100644 << 16
            archive.writestr(entry, path.read_bytes(), compresslevel=9)
    return HTML_OUTPUT, ZIP_OUTPUT


if __name__ == "__main__":
    for output in build():
        print(output.relative_to(ROOT))
